# NOME DA ROTINA
name: Entrega Contínua

# QUANDO SERÁ EXECUTADO: NA CHAMADA DO ARQUIVO
on:
  workflow_call:

# TAREFAS
jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticando credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: OBTER ARQUIVO DA TASK
        run: aws ecs describe-task-definition --task-definition task-api-go --query taskDefinition > task-definition.json
